// <!DOCTYPE html>
// <html lang="en">
// 	<head>
// 		<meta charset="UTF-8" />
// 		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
// 		<title>TOP BattleShip</title>
// 		<link rel="stylesheet" href="./styles/main.css" />
// 	</head>
// 	<body>
// 		<div class="container">
// 			<div class="message-container">
// 				<!-- <p class="message">Computer's turn, Please wait...</p> -->
// 				<p class="message">Your turn, Please choose your next attack...</p>
// 				<!-- <p class="message">Ship down, 3 more ships to go.</p> -->
// 			</div>
// 			<div class="game-container">
// 				<div class="player-container">
// 					<h3 class="grid-title">Player Waters</h3>
// 					<div class="grid-container">
// 						<div id="player-grid" class="grid">
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 						</div>
// 						<div class="col-header">
// 							<div class="col">0</div>
// 							<div class="col">1</div>
// 							<div class="col">2</div>
// 							<div class="col">3</div>
// 							<div class="col">4</div>
// 							<div class="col">5</div>
// 							<div class="col">6</div>
// 							<div class="col">7</div>
// 							<div class="col">8</div>
// 							<div class="col">9</div>
// 						</div>
// 						<div class="row-header">
// 							<div class="row">0</div>
// 							<div class="row">1</div>
// 							<div class="row">2</div>
// 							<div class="row">3</div>
// 							<div class="row">4</div>
// 							<div class="row">5</div>
// 							<div class="row">6</div>
// 							<div class="row">7</div>
// 							<div class="row">8</div>
// 							<div class="row">9</div>
// 						</div>
// 					</div>
// 				</div>
// 				<div class="computer-container">
// 					<h3 class="grid-title">Enemy Waters</h3>
// 					<div class="grid-container">
// 						<div id="enemy-grid" class="grid">
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 							<div class="cell"></div>
// 						</div>
// 						<div class="col-header">
// 							<div class="col">0</div>
// 							<div class="col">1</div>
// 							<div class="col">2</div>
// 							<div class="col">3</div>
// 							<div class="col">4</div>
// 							<div class="col">5</div>
// 							<div class="col">6</div>
// 							<div class="col">7</div>
// 							<div class="col">8</div>
// 							<div class="col">9</div>
// 						</div>
// 						<div class="row-header">
// 							<div class="row">0</div>
// 							<div class="row">1</div>
// 							<div class="row">2</div>
// 							<div class="row">3</div>
// 							<div class="row">4</div>
// 							<div class="row">5</div>
// 							<div class="row">6</div>
// 							<div class="row">7</div>
// 							<div class="row">8</div>
// 							<div class="row">9</div>
// 						</div>
// 					</div>
// 				</div>
// 			</div>
// 		</div>
// 	</body>
// </html>
